// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHNQ5iaAjfNf2N4lH5TBCttE6xaXmoMoM',
    appId: '1:282080671926:web:f674faca2656c1c861ce17',
    messagingSenderId: '282080671926',
    projectId: 'my-flutter-app-7ebd5',
    authDomain: 'my-flutter-app-7ebd5.firebaseapp.com',
    storageBucket: 'my-flutter-app-7ebd5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD69xy8sgnjWTiDgHTZl41zYi3GGFMJQtI',
    appId: '1:282080671926:android:db70aceed4245f7f61ce17',
    messagingSenderId: '282080671926',
    projectId: 'my-flutter-app-7ebd5',
    storageBucket: 'my-flutter-app-7ebd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4G3t3W4SSqSslACunbp1xMeiJpWghxSI',
    appId: '1:282080671926:ios:e68aca3a50b8dbd561ce17',
    messagingSenderId: '282080671926',
    projectId: 'my-flutter-app-7ebd5',
    storageBucket: 'my-flutter-app-7ebd5.firebasestorage.app',
    iosBundleId: 'com.example.riceGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4G3t3W4SSqSslACunbp1xMeiJpWghxSI',
    appId: '1:282080671926:ios:e68aca3a50b8dbd561ce17',
    messagingSenderId: '282080671926',
    projectId: 'my-flutter-app-7ebd5',
    storageBucket: 'my-flutter-app-7ebd5.firebasestorage.app',
    iosBundleId: 'com.example.riceGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHNQ5iaAjfNf2N4lH5TBCttE6xaXmoMoM',
    appId: '1:282080671926:web:9e7e185c10d130e661ce17',
    messagingSenderId: '282080671926',
    projectId: 'my-flutter-app-7ebd5',
    authDomain: 'my-flutter-app-7ebd5.firebaseapp.com',
    storageBucket: 'my-flutter-app-7ebd5.firebasestorage.app',
  );
}
